# Generated by Django 6.0.7 on 2026-08-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_bookmarked_by_post_category_post_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bean_amount',
            field=models.CharField(blank=True, max_length=30, verbose_name='원두량'),
        ),
        migrations.AddField(
            model_name='post',
            name='brew_time',
            field=models.CharField(blank=True, max_length=30, verbose_name='추출 시간'),
        ),
        migrations.AddField(
            model_name='post',
            name='brew_tool',
            field=models.CharField(blank=True, max_length=80, verbose_name='추출 도구'),
        ),
        migrations.AddField(
            model_name='post',
            name='water_amount',
            field=models.CharField(blank=True, max_length=30, verbose_name='물양'),
        ),
        migrations.AddField(
            model_name='post',
            name='water_temperature',
            field=models.CharField(blank=True, max_length=30, verbose_name='물 온도'),
        ),
    ]
